spring.application.name=Educational Quality Project

# conexão antiga da Ash
spring.data.mongodb.uri=mongodb+srv://ashadmin:Ash123456@cluster0.oicuoju.mongodb.net/hogwartslibrary?appName=Cluster0

server.port=8080
# conexão lavys
#spring.data.mongodb.uri=mongodb+srv://lavigniaoleite_db_user:DBfdUeAx8oxWS5qm@cluster0.n3dj71l.mongodb.net/hogwartslibrary?retryWrites=true&w=majority&appName=Cluster0